pipeline:
#  build:
#    image: ${IMAGE}
#    commands:
#      - pip install --upgrade pip setuptools wheel
#      - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
#      - pip wheel -r test-requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
#      - pip install --use-wheel --no-index --find-links=wheeldir -r requirements.txt
#      - pip install --use-wheel --no-index --find-links=wheeldir -r test-requirements.txt
#      - python setup.py install
#      - flake8 dronedemo
#      - mkdir -p coverage
#      - nosetests -v tests/

  ecr:
    image: plugins/ecr
    secret_key: ${ECR_SECRET_KEY}
    access_key: ${ECR_ACCESS_KEY}
    repo: 995121555896.dkr.ecr.us-east-1.amazonaws.com/cloudlock/test-sit-ci-built-svc
    dockerfile: ./Dockerfile
    context: .
    commands:
      - echo $AWS_ACCESS_KEY_ID
      - echo $${ECR_SECRET_KEY}
    environment:
      - AWS_ACCESS_KEY_ID=${ECR_SECRET_KEY}
      - AWS_SECRET_ACCESS_KEY=${ECR_ACCESS_KEY}

matrix:
  IMAGE:
    - python:3.5.1-alpine
